AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  BucketName:
    Type: String
    Description: my-unique-bucket-name-shironkurian-12345
  Versioning:
    Type: String
    AllowedValues:
      - Enabled
      - Suspended
    Default: Enabled
    Description: S3 bucket versioning state.

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: !Ref Versioning
