AWSTemplateFormatVersion: '2010-09-09'
Description: "CloudFormation template to create an S3 bucket with versioning"

Parameters:
  BucketName:
    Description: "Shiron2025Lab3"
    Type: String
  VersioningStatus:
    Description: "Versioning status (Enabled or Suspended)"
    Type: String
    AllowedValues:
      - Enabled
      - Suspended
    Default: Suspended

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: !Ref VersioningStatus

Outputs:
  BucketName:
    Description: "The name of the created bucket"
    Value: !Ref S3Bucket